### ISSUE TITLE
Update Libvirt to version 4.0RC1

### ISSUE THREAD

**Issue by jesltc** [open-power-host-os/libvirt#11]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=163673 </cde:info>

Track updating libvirt to version 4.0RC1

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-01-25 03:30:15 EDT-------
We have run a round of sanity regression with this libvirt level on devel when it was having kernel kernel-4.14.0-1. Based on result libvirt 4.0 was pushed to release branch.
