### ISSUE TITLE
[Feature]To enable libvirt xml tags for spapr machine capabilities cap-{sbbc,cfpc,ibs} for meltdown/spectre fixes

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/libvirt#13]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164505 </cde:info>

qemu-kvm adds new three machine properties to propagate the meltdown/spectre fixes to the guest,
libvirt needs to have it enabled for the user to utilise these machine capabilities.

Host Env:
4.15.0-3.dev.gitd34a158.el7.centos.ppc64le
libvirt-4.0.0-2.dev.git5e6f8a1.el7.centos.ppc64le
qemu-2.11.50-1.dev.gita815ffa.el7.centos.ppc64le

```
# qemu-kvm -M pseries,help
....
pseries-2.12.cap-sbbc=string (Speculation Barrier Bounds Checking (broken, workaround, fixed))
pseries-2.12.cap-cfpc=string (Cache Flush on Privilege Change (broken, workaround, fixed))
pseries-2.12.cap-ibs=string (Indirect Branch Serialisation (broken, workaround, fixed))
```
Refer this qemu issue that has explanation of why this needed.
[https://github.com/open-power-host-os/qemu/issues/35](url)

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-02-09 12:01:45 EDT-------
Shivapbh and I will have a look.

**Comment by sathnaga** [comment]
Upstream link which implements rfc patch: https://www.mail-archive.com/libvir-list@redhat.com/msg157433.html

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-02-27 04:45:33 EDT-------
Any updates here?

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-02-27 12:58:05 EDT-------
We'll pull this in when we update to libvirt 4.1. We will do that when we either integrate the relevant parts of 2.11.1 or go to 2.12-rc. We will discuss this on sloack.

------- Comment From seg@us.ibm.com 2018-02-27 12:58:35 EDT-------
We will either integrate the relevant parts of 2.11.1 or go to 2.12-rc. We will discuss this on slack.

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-02-28 15:07:57 EDT-------
sorry  about bogus comment 6. Anyway, I think we're waiting for a qemu 2.12-rc, which should be ready in 3 weeks for Sprint 9, If there's some compelling reason to bring in the libvirt patches earlier, please share them here.

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-03-01 16:00:24 EDT-------
Now that the patches are final, perhaps it would be worth it to bring them into hostos so the testers could have at it for sprint 8 testing. In Sprint 9 we get them from upstream in a v4.1 merge.
