### ISSUE TITLE
libvirt: virsh capabilities output missing cpu cache info due to "virQEMUCapsInit:1212 : Failed to get host CPU cache info"

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/libvirt#15]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=166343 </cde:info>

libvirt fails to get and display the cpu cache info in virsh capabilities output and throws warning, "virQEMUCapsInit:1212 : Failed to get host CPU cache info".

Env:
libvirt: libvirt-4.0.0-2.dev.git5e6f8a1.el7.centos.ppc64le
host kernel: 4.16.0-1.rc7.dev.git58079f0.el7.centos.ppc64le
qemu: qemu-2.11.50-3.dev.git59cc362.el7.centos.ppc64le

Actual capabilities output:
```
  </cpus>
        </cell>
      </cells>
    </topology>
.....
..... ----------------------NOK
.....
    <secmodel>
  
```

Expected(taken from x86):
```
   </cells>
    </topology>
    <cache>
      <bank id='0' level='3' type='both' size='3072' unit='KiB' cpus='0-3'/>
    </cache>
    <secmodel>
```

Reason: while parsing cpu/cache sysfs entries libvirt in https://github.com/libvirt/libvirt/blob/master/src/conf/capabilities.c#L1611 (virCapabilitiesInitCaches) expects certain files to present such as `id,shared_cpu_list` to be present which is looks like  not available in power systems, hence it fails to get info.

power9:
```
ls -l
total 0
-r--r--r-- 1 root root 65536 Apr  2 08:01 coherency_line_size
-r--r--r-- 1 root root 65536 Apr  2 08:01 level
-r--r--r-- 1 root root 65536 Apr  2 08:01 number_of_sets
-r--r--r-- 1 root root 65536 Apr  2 08:01 shared_cpu_map
-r--r--r-- 1 root root 65536 Apr  2 08:01 size
-r--r--r-- 1 root root 65536 Apr  2 08:01 type
-r--r--r-- 1 root root 65536 Apr  2 08:01 ways_of_associativity
```

x86:
```
 ls -l
total 0
-r--r--r--. 1 root root 4096 Apr  2 16:17 coherency_line_size
-r--r--r--. 1 root root 4096 Apr  2 16:17 id
-r--r--r--. 1 root root 4096 Apr  2 16:17 level
-r--r--r--. 1 root root 4096 Apr  2 16:17 number_of_sets
-r--r--r--. 1 root root 4096 Apr  2 16:17 physical_line_partition
drwxr-xr-x. 2 root root    0 Apr  2 17:31 power
-r--r--r--. 1 root root 4096 Apr  2 16:17 shared_cpu_list
-r--r--r--. 1 root root 4096 Apr  2 16:17 shared_cpu_map
-r--r--r--. 1 root root 4096 Apr  2 16:17 size
-r--r--r--. 1 root root 4096 Apr  2 16:17 type
-rw-r--r--. 1 root root 4096 Apr  2 16:17 uevent
-r--r--r--. 1 root root 4096 Apr  2 16:17 ways_of_associativity

```

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-04-02 12:06:05 EDT-------
That code has been highly reworked recently (the function virQEMUCapsInit does not even exist, now). We are about to merge in libvirt 4.2.0 anyway, so let's wait and see what happens after we do that. 

Shiva, let's use this bug to track that merge.

**Comment by sathnaga** [comment]
I am able to reproduce this with latest libvirt aswell.
Host Env:
4.16.0-2.dev.gitb24758c.el7.centos.ppc64le
libvirt-4.2.0-2.dev.gitbf217de.el7.centos.ppc64le
qemu-system-ppc-2.11.91-1.dev.git46a0689.el7.centos.ppc64le

```
libvirtd warning log during libvirtd restart:
2018-04-10 14:27:45.277+0000: 58903: warning : virQEMUCapsInit:1222 : Failed to get host CPU cache info
2018-04-10 14:27:45.517+0000: 58903: warning : virLXCDriverCapsInit:85 : Failed to get host CPU cache info

virsh capabilities output
....
...
          <cpus num='5'>
            <cpu id='120' socket_id='17' core_id='2208' siblings='120'/>
            <cpu id='128' socket_id='17' core_id='2216' siblings='128'/>
            <cpu id='136' socket_id='17' core_id='2224' siblings='136'/>
            <cpu id='144' socket_id='17' core_id='2272' siblings='144'/>
            <cpu id='152' socket_id='17' core_id='2288' siblings='152'/>
          </cpus>
        </cell>
      </cells>
    </topology>
                         ===========NOK
    <secmodel>
      <model>selinux</model>
      <doi>0</doi>
      <baselabel type='kvm'>system_u:system_r:svirt_t:s0</baselabel>
      <baselabel type='qemu'>system_u:system_r:svirt_tcg_t:s0</baselabel>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type='kvm'>+107:+107</baselabel>
      <baselabel type='qemu'>+107:+107</baselabel>
    </secmodel>
  </host>
```

**Comment by cdeadmin** [comment]
------- Comment From shivapbh@in.ibm.com 2018-04-18 04:33:22 EDT-------
Hi Satheesh, 

Can you confirn if this has ever worked? I see on the recent ppc kernels(4.[15|16|13]), the &quot;id&quot; attribute is not there in  /sys/devices/system/cpu/cpu&lt;X&gt;/cache/index&lt;X&gt;/

So, want to know for sure if this is a regression with recent kernel or this just has never been there.

Thanks,
Shiva

**Comment by sathnaga** [comment]
Hi Shiva,

I just verified with host kernel level `3.10.0-693.24.1.el7.ppc64le`(Rhel7.4.z), `id' attribute is not there.
libvirt-3.2.0-14.el7_4.9.ppc64le

```
ls -l  /sys/devices/system/cpu/cpu0/cache/index0/
total 0
-r--r--r-- 1 root root 65536 Apr 18 14:25 coherency_line_size
-r--r--r-- 1 root root 65536 Apr  5 12:13 level
-r--r--r-- 1 root root 65536 Apr 18 14:25 number_of_sets
-r--r--r-- 1 root root 65536 Apr  5 12:13 shared_cpu_map
-r--r--r-- 1 root root 65536 Apr  5 12:13 size
-r--r--r-- 1 root root 65536 Apr  5 12:13 type
-r--r--r-- 1 root root 65536 Apr 18 14:25 ways_of_associativity
```
failed to display in `virsh capabilities` there aswell

```
          </cpus>
        </cell>
      </cells>
    </topology>
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
```

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-04-23 21:54:11 EDT-------
I would also add that given that this NEVER worked on Power, I think we need justification for a severity greater than &quot;normal&quot; (or even &quot;low&quot;).
