### ISSUE TITLE
[HostOS] [4.17] Migration failed with "error: operation failed: migration out job: unexpectedly failed"

### ISSUE THREAD

**Issue by balamuruhans** [open-power-host-os/libvirt#16]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=169384 </cde:info>

MultiVM Migration with stress failed with "error: operation failed: migration out job: unexpectedly failed".

**Test setup:**
1. Install and Boot 3 VMs (vms1, vms2, vms3) in the environment (all 3 vms xml are attached)
2. In all the VMs stress tool is installed by downloaded from http://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz and  cd /home/stress-1.0.4/;./configure && make install
3. memory stress is ran inside the VMs,
`# nohup stress --vm 4 --vm-bytes 128M --vm-keep --timeout 3600 &`
4. Perform migration from source to target one by one,
```

**vms3 failed to migrate on a thread,**
/bin/virsh -c 'qemu:///system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms3 --desturi qemu+ssh://9.47.70.203/system running on a thread
19:24:19 DEBUG| [stderr] error: operation failed: migration out job: unexpectedly failed

**vms2 succeeded to migrate**
19:54:35 INFO | Command '/bin/virsh -c 'qemu:///system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms2 --desturi qemu+ssh://9.47.70.203/system' finished with 0 after 1816.05531406s
19:54:35 DEBUG| status: 0

**vms1 succeeded to migrate**
20:12:24 INFO | Command '/bin/virsh -c 'qemu:///system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms1 --desturi qemu+ssh://9.47.70.203/system' finished with 0 after 1069.34284902s
20:12:24 DEBUG| status: 0

```
The issue was observed **twice** while running memory stress on the VM then migrate, as well while running memory stress on source host (# nohup stress --vm 4 --vm-bytes 54310528 --vm-keep --timeout 3600 &) then migrate VMs

> virsh.migrate_stress.orderly_migration.run_stress_app.stress_tool_in_vms.memory_stress.precopy.set_memory_1 -> TestFail
> virsh.migrate_stress.orderly_migration.run_stress_app.stress_tool_on_host.half_memory.memory_stress.postcopy.set_memory_2 -> TestFail

**Logs attachment:**
1. Libvirtd Logs for both occurrence.
2. source and target host sosreport
3. All the VMs domain XML

**System configuration:**
```
Host Kernel: 4.17.0-1.dev.git5ce3eac.el7.ppc64le
Guest Kernel: 4.17.0-1.dev.git5ce3eac.el7.ppc64le
Qemu: qemu-2.12.0-2.dev.gitd36f3ee.el7.ppc64le
SLOF: SLOF-20171214-2.dev.gitc2a331f.el7.centos.noarch
Libvirt: libvirt-4.3.0-1.dev.git3096ff1.el7.ppc64le
```

**Comment by balamuruhans** [comment]
**VM domain XML:**
[vms1.txt](https://github.com/open-power-host-os/libvirt/files/2151778/vms1.txt)
[vms2.txt](https://github.com/open-power-host-os/libvirt/files/2151779/vms2.txt)
[vms3.txt](https://github.com/open-power-host-os/libvirt/files/2151780/vms3.txt)

**Comment by balamuruhans** [comment]
**Libvirtd debug logs:**
1. [libvirtd.tar.gz](https://github.com/open-power-host-os/libvirt/files/2151785/libvirtd.tar.gz)
2. [libvirtd.tar.gz](https://github.com/open-power-host-os/libvirt/files/2151789/libvirtd.tar.gz)

**Comment by balamuruhans** [comment]
**Sosreport:**
source - [source_sosreport.tar.gz](https://github.com/open-power-host-os/libvirt/files/2151796/source_sosreport.tar.gz)
target - sosreport is huge and couldn't upload. I have it in server, please ping me privately

**Comment by cdeadmin** [comment]
------- Comment From viparash@in.ibm.com 2018-07-03 05:24:45 EDT-------
Host Kernel: 4.17.0-1.dev.git5ce3eac.el7.ppc64le
Guest Kernel: 4.17.0-1.dev.git5ce3eac.el7.ppc64le
Qemu: qemu-2.12.0-2.dev.gitd36f3ee.el7.ppc64le
SLOF: SLOF-20171214-2.dev.gitc2a331f.el7.centos.noarch
Libvirt: libvirt-4.3.0-1.dev.git3096ff1.el7.ppc64le

Hi Shiva,

Can you please have a look at this ?
Both source and target have above libvirt
and qemu levels.
