### ISSUE TITLE
Snapshot-revert making the attached interface persistent in the guest

### ISSUE THREAD

**Issue by MalleshKoti** [open-power-host-os/libvirt#2]
Issue:
======
Snapshot-revert of a hot plugged guest making the attached interface persistent.

Steps to recreate:
===============
XML used for attachment:
cat network.xml 
```
<?xml version='1.0' encoding='UTF-8'?>
  <interface type="network">
  <source network="default" />
  <model type="virtio" />
  <mac address="9a:2e:c5:fb:84:06" />
</interface>
```
1. Create a guest say VM1
2. Attach a virtual NIC to the guest : 
    virsh attach-device VM1 network.xml --live
    attached interface will be seen in the guest.
3. Take a snapshot of the guest :
    virsh snapshot-create VM1
    Domain snapshot 1505299135 created
4. Destroy the guest
5. now, revert back the snapshot:
    virsh snapshot-revert VM1 1505299135
    Interface is seen in the guest.
6. Now destroy the guest and start it again --> Interface is still seen in the guest. It is making the attach       persistent.

<cde:info> Mirrored with LTC bug #159269 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From magadagi@in.ibm.com 2017-09-26 07:00:59 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-05-25 12:42:21 EDT-------
Shiva (or Madhu) - have the patches been reposted? What's going on with this?
