### ISSUE TITLE
Power8: KVM guests randomly fail to start

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/libvirt#4]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=160014 </cde:info>

I was trying to boot 20 guests, one after other, in a loop. Among 20, 4 of the guests failed to boot.. below is the run log:

[root@ltc-test-ci2 srikanth]# for i in `virsh list --all | grep -i virt-vm0-clone | awk '{print $2}'`; do virsh start $i; done
Domain virt-vm0-clone1 started

Domain virt-vm0-clone10 started

Domain virt-vm0-clone11 started

Domain virt-vm0-clone12 started

error: Failed to start domain virt-vm0-clone13
error: Activation of org.freedesktop.machine1 timed out

Domain virt-vm0-clone14 started

Domain virt-vm0-clone15 started

Domain virt-vm0-clone16 started

Domain virt-vm0-clone17 started

error: Failed to start domain virt-vm0-clone18
error: Activation of org.freedesktop.machine1 timed out

Domain virt-vm0-clone19 started

Domain virt-vm0-clone2 started

Domain virt-vm0-clone20 started

Domain virt-vm0-clone3 started

error: Failed to start domain virt-vm0-clone4
error: Activation of org.freedesktop.machine1 timed out

Domain virt-vm0-clone5 started

Domain virt-vm0-clone6 started

Domain virt-vm0-clone7 started

Domain virt-vm0-clone8 started

error: Failed to start domain virt-vm0-clone9
error: Activation of org.freedesktop.machine1 timed out

> virsh list
 Id    Name                           State
----------------------------------------------------
 26    virt-vm0-clone1                running
 27    virt-vm0-clone10               running
 28    virt-vm0-clone11               running
 29    virt-vm0-clone12               running
 31    virt-vm0-clone14               running
 32    virt-vm0-clone15               running
 33    virt-vm0-clone16               running
 34    virt-vm0-clone17               running
 36    virt-vm0-clone19               running
 37    virt-vm0-clone2                running
 38    virt-vm0-clone20               running
 39    virt-vm0-clone3                running
 41    virt-vm0-clone5                running
 42    virt-vm0-clone6                running
 43    virt-vm0-clone7                running
 44    virt-vm0-clone8                running

> virsh list --all
 Id    Name                           State
----------------------------------------------------
 26    virt-vm0-clone1                running
 27    virt-vm0-clone10               running
 28    virt-vm0-clone11               running
 29    virt-vm0-clone12               running
 31    virt-vm0-clone14               running
 32    virt-vm0-clone15               running
 33    virt-vm0-clone16               running
 34    virt-vm0-clone17               running
 36    virt-vm0-clone19               running
 37    virt-vm0-clone2                running
 38    virt-vm0-clone20               running
 39    virt-vm0-clone3                running
 41    virt-vm0-clone5                running
 42    virt-vm0-clone6                running
 43    virt-vm0-clone7                running
 44    virt-vm0-clone8                running
 -     virt-tests-vm1                 shut off
 -     virt-vm0                       shut off
 -     virt-vm0-clone13               shut off
 -     virt-vm0-clone18               shut off
 -     virt-vm0-clone4                shut off
 -     virt-vm0-clone9                shut off

> virsh start virt-vm0-clone13
Domain virt-vm0-clone13 started

> virsh start virt-vm0-clone18
Domain virt-vm0-clone18 started

> virsh start virt-vm0-clone4
virsh start Domain virt-vm0-clone4 started

> virsh start virt-vm0-clone9
Domain virt-vm0-clone9 started

This bug is to debug why these guests fail to boot first time.

**Comment by cdeadmin** [comment]
------- Comment From viparash@in.ibm.com 2017-10-12 06:20:55 EDT-------
I tried two times and each time same 4 guests (13, 18, 4, 9) 
fail to start in first attempt.

------- Comment From viparash@in.ibm.com 2017-10-12 06:26:21 EDT-------
[root@ltc-test-ci2 ~]# for i in `virsh list --all | grep -i virt-vm0-clone | awk '{print $2}'`; do echo &quot;Starting $i...&quot;; virsh start $i; sleep 1; done
Starting virt-vm0-clone1...
Domain virt-vm0-clone1 started

Starting virt-vm0-clone10...
Domain virt-vm0-clone10 started

Starting virt-vm0-clone11...
Domain virt-vm0-clone11 started

Starting virt-vm0-clone12...
Domain virt-vm0-clone12 started

Starting virt-vm0-clone13...
Domain virt-vm0-clone13 started

Starting virt-vm0-clone14...
Domain virt-vm0-clone14 started

Starting virt-vm0-clone15...
Domain virt-vm0-clone15 started

Starting virt-vm0-clone16...
Domain virt-vm0-clone16 started

Starting virt-vm0-clone17...
Domain virt-vm0-clone17 started

Starting virt-vm0-clone18...
Domain virt-vm0-clone18 started

Starting virt-vm0-clone19...
Domain virt-vm0-clone19 started

Starting virt-vm0-clone2...
Domain virt-vm0-clone2 started

Starting virt-vm0-clone20...
Domain virt-vm0-clone20 started

Starting virt-vm0-clone3...
Domain virt-vm0-clone3 started

Starting virt-vm0-clone4...
Domain virt-vm0-clone4 started

Starting virt-vm0-clone5...
Domain virt-vm0-clone5 started

Starting virt-vm0-clone6...
Domain virt-vm0-clone6 started

Starting virt-vm0-clone7...
Domain virt-vm0-clone7 started

Starting virt-vm0-clone8...
Domain virt-vm0-clone8 started

Starting virt-vm0-clone9...
Domain virt-vm0-clone9 started

[root@ltc-test-ci2 ~]# 

[root@ltc-test-ci2 ~]# virsh list
 Id    Name                           State
----------------------------------------------------
 110   virt-vm0-clone1                running
 111   virt-vm0-clone10               running
 112   virt-vm0-clone11               running
 113   virt-vm0-clone12               running
 114   virt-vm0-clone13               running
 115   virt-vm0-clone14               running
 116   virt-vm0-clone15               running
 117   virt-vm0-clone16               running
 118   virt-vm0-clone17               running
 119   virt-vm0-clone18               running
 120   virt-vm0-clone19               running
 121   virt-vm0-clone2                running
 122   virt-vm0-clone20               running
 123   virt-vm0-clone3                running
 124   virt-vm0-clone4                running
 125   virt-vm0-clone5                running
 126   virt-vm0-clone6                running
 127   virt-vm0-clone7                running
 128   virt-vm0-clone8                running
 129   virt-vm0-clone9                running

[root@ltc-test-ci2 ~]# virsh list | grep -c running
20
[root@ltc-test-ci2 ~]# 

Gave a 1 second delay between starting guests and 
all guests started successfully in first attempt.

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-02-15 01:46:59 EDT-------
Currently this issue seems to be not getting recreated on my host. Will reopen if I see this issue again.
