### ISSUE TITLE
wrong eta during virt-clone process

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/libvirt#6]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=160987 </cde:info>

virt-clone gives erroneous ETA like below:

'''# virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le-clone-21.qcow2'                          26% [================                                             ]   45 B/s | 8.0 GB  147534:47:08 ETA
...

..

virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le-clone-20.qcow2'                   26% [==============                                        ]  0.0 B/s | 8.0 GB  1179105773046988800:00:00 ETA'''

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2017-11-09 14:53:05 EDT-------
Changing the update period from every 0.3 seconds to every 0.9 seconds seems to have fixed the problem. However, whatever happened, now going back to the original code, the symptoms seem no longer to be reproducible, so it's not really clear what happened. Unless we can consistently recreate the problem, I don't think we can really even try to propose changes.  I'm not sure what, if anything, can be done at the moment. Can you recreate?

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-11-09 22:51:32 EDT-------
(In reply to comment #4)
&gt; Changing the update period from every 0.3 seconds to every 0.9 seconds seems
&gt; to have fixed the problem. However, whatever happened, now going back to the
&gt; original code, the symptoms seem no longer to be reproducible, so it's not
&gt; really clear what happened. Unless we can consistently recreate the problem,
&gt; I don't think we can really even try to propose changes.  I'm not sure what,
&gt; if anything, can be done at the moment. Can you recreate?

I can consistently recreate this issue with/without stress on my host.

------- Comment From bssrikanth@in.ibm.com 2017-11-09 22:52:27 EDT-------
even without any stress running on host I am able to recreate on my server

[root@powerkvm4-lp1 srikanth]# virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le_mod-clone.qcow2'                         26% [================                                             ]   57 B/s | 8.0 GB  116063:52:39 ETA

it actually starts happening when it reaches 26%

[root@powerkvm4-lp1 srikanth]# virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le_mod-clone.qcow2'                       26% [===============-                                           ]  0.0 B/s | 8.0 GB  3396240674:22:54 ETA

[root@powerkvm4-lp1 srikanth]# virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le_mod-clone.qcow2'                      26% [===============                                           ]  0.0 B/s | 8.0 GB  151905947016:51:49 ETA

but within a minute or so it completes

[root@powerkvm4-lp1 srikanth]# virt-clone --original hostos_vm --auto-clone
Allocating 'hostos-3.0-ppc64le_mod-clone.qcow2'                                                                                                          |  30 GB  00:03:57     

Clone 'hostos_vm-clone21' created successfully.

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2017-11-10 01:38:40 EDT-------
I will look again in a few hours (morning, my time). It's very odd - it just stopped showing the symptoms for a while. Also, maybe unsurprisingly, adding a print statement to the progress.py code (which seems to be the source of the problem) changes the timing enough to stop showing the problem.
